spring:
  kafka:
    admin:
      properties:
        bootstrap.servers: kafka:9092
    topic:
      topics-to-create: waggle-chat
      partitions: 6
      replication-factor: 3


kafka:
  waggle:
    topic: waggle-chat
    groupId: waggle-chat-group
    broker: localhost:9092